### ISSUE TITLE
PoC of a pattern editor

### ISSUE THREAD

**Issue by kikuomax** [kikuomax/amidz#12]
Complete a PoC of a pattern editor.

Features to implement in this issue.
- [x] Interface to select a row to edit (#32).
- [x] Interface to add a row (#33).
- [x] Interface to remove a row (#34).
- [x] Interface to save a pattern (#35).
